/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as annualBudgetSol from "./AnnualBudget.sol";
export type { annualBudgetSol };
import type * as erc20MaticSol from "./ERC20Matic.sol";
export type { erc20MaticSol };
