/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20MaticSol from "./ERC20Matic.sol";
export type { erc20MaticSol };
export type { AnnualBudget } from "./AnnualBudget";
